version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: lombriaventura_db
    environment:
      MYSQL_ROOT_PASSWORD: Lombriaventura
      MYSQL_DATABASE: lombriaventura
      MYSQL_USER: lombriadmin
      MYSQL_PASSWORD: Lombriaventura*123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lombriaventura_phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data: